import { ArrowRight, BookOpen, GitBranch, Package, Terminal } from 'lucide-react'
import { CodePanel, NavLink, SectionHeading } from './ui'

const packageName = '@battincik/coreor-datatable'
const install = `# After the first npm release\nnpm install ${packageName}\n\n# React 18 or 19 and react-dom are peer dependencies`
const sample = `// app/layout.tsx (Next.js) or main.tsx (Vite)\nimport '${packageName}/styles.css'\n\n// components/customers-table.tsx\n'use client'\nimport { useState } from 'react'\nimport { EnterpriseGrid, type GridColumn } from '${packageName}'\n\ntype Customer = { id: number; name: string; status: string; balance: number }\nconst columns: GridColumn<Customer>[] = [\n  { key: 'name', title: 'Customer', kind: 'text', editable: true },\n  { key: 'status', title: 'Status', kind: 'status', editable: true,\n    options: ['active', 'pending', 'blocked'] },\n  { key: 'balance', title: 'Balance', kind: 'price', editable: true,\n    aggregate: 'sum', cellOptions: { currency: 'TRY', locale: 'tr-TR' } },\n]\n\nexport function CustomersTable() {\n  const [rows, setRows] = useState<Customer[]>([\n    { id: 1, name: 'Acme', status: 'active', balance: 1250 },\n    { id: 2, name: 'Coreor', status: 'pending', balance: 980 },\n  ])\n  return <EnterpriseGrid title="Customers" columns={columns} data={rows}\n    onDataChange={setRows} pagination={{ initialPageSize: 25 }}\n    height={520} filename="customers.csv" />\n}`
const server = `import type { GridQuery, GridExportRequest } from '${packageName}'\n\n// Keep query, result rows and total on the client. Query the API when\n// search, sorting, filters or pagination change.\nconst [query, setQuery] = useState<GridQuery>({\n  search: '', sorting: [], filters: [], pageIndex: 0, pageSize: 25,\n})\n\n<EnterpriseGrid data={pageRows} columns={columns} serverMode\n  totalRows={matchingRowCount} onQueryChange={setQuery}\n  onExportRequest={async (request: GridExportRequest) => {\n    // Server returns the requested selection or all filtered rows.\n    const response = await fetch('/api/export', {\n      method: 'POST', headers: { 'Content-Type': 'application/json' },\n      body: JSON.stringify(request),\n    })\n    if (!response.ok) throw new Error('Export failed')\n    return response.blob()\n  }}\n/>`
const sections = [
  { slug:'installation', title:'Installation', icon:Package, description:'Install the package, load its CSS once and prepare React.' },
  { slug:'usage', title:'Usage & API', icon:BookOpen, description:'Typed columns, controlled data, server requests and exports.' },
  { slug:'publishing', title:'Publishing', icon:Terminal, description:'A repeatable release flow for the package maintainer.' },
] as const
export function DocsPage({ path, navigate }: {path:string; navigate:(path:string)=>void}) {
  const active = path.split('/')[2]
  return <><SectionHeading eyebrow="DEVELOPER GUIDE / REACT" title={active ? sections.find(s => s.slug === active)?.title ?? 'Documentation' : 'Documentation'} description="Copy a working snippet, customize columns and wire the table to your own data."/>
    <div className="docs-layout"><nav className="docs-menu" aria-label="Documentation sections">{sections.map(s => <NavLink key={s.slug} to={`/docs/${s.slug}`} active={s.slug===active} navigate={navigate}><s.icon size={17}/><span>{s.title}</span><ArrowRight size={14}/></NavLink>)}</nav>
    <div className="docs-content">
      {!active && <><div className="docs-intro"><span>START HERE</span><h2>A useful grid in a few lines.</h2><p>Bring your own rows and column definitions. Keep edits in your state and add server handlers when the data set outgrows the browser.</p><NavLink to="/maker" navigate={navigate} className="sc-primary">Open Table Maker <ArrowRight size={15}/></NavLink></div><CodePanel code={sample}/></>}
      {active === 'installation' && <><h2>Install the package</h2><p>The npm package is prepared in this repository. Its first public release is pending. Use the local package after cloning until it is published.</p><CodePanel code={install}/><h3>Develop from the repository</h3><CodePanel code={`git clone https://github.com/battincik/coreor-datatable.git\ncd coreor-datatable\nnpm install\nnpm run build:lib\nnpm run dev`}/><p>React and React DOM are peer dependencies. Import the stylesheet once at your app root. For Next.js, place your interactive table inside a client component with <code>'use client'</code>.</p></>}
      {active === 'usage' && <><h2>Start with typed columns</h2><p>Every column connects a key of your row type to a renderer and optional editor, filter or aggregation. The grid accepts new <code>data</code> and <code>columns</code> props at runtime.</p><CodePanel code={sample}/><h3>Server pagination and export</h3><p>With <code>serverMode</code>, pass only the active page and the total matching row count. Your API handles sorting, filters and export requests.</p><CodePanel code={server}/><h3>Explore the full API</h3><p>See <code>README.md</code> and <code>docs/API.md</code> in the repository for all props, cell options, raw value shapes and limitations.</p></>}
      {active === 'publishing' && <><h2>Release to npm</h2><p>The public package name is <code>{packageName}</code>. The <code>@battincik</code> scope must be controlled by your npm account. GitHub and npm accounts are separate.</p><CodePanel code={`npm login\nnpm whoami\nnpm test\nnpm run build:lib\nnpm run pack:dry\n# Change packages/coreor-datatable/package.json version for each release\nnpm publish ./packages/coreor-datatable --access public`}/><p>Use a new semantic version for every release. Enable npm account 2FA or configure a trusted publisher for automated releases. Full steps are in <code>docs/PUBLISHING.md</code>.</p><a href="https://github.com/battincik/coreor-datatable" target="_blank" rel="noreferrer" className="docs-github"><GitBranch size={17}/> View the repository <ArrowRight size={15}/></a></>}
    </div></div>
  </>
}
